;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

(package! beacon)
(package! rainbow-mode)
(package! dired-open)
(package! org-auto-tangle)
(package! dired-subtree)
(package! dirvish)
(package! org-modern)
(package! olivetti)
(package! reformatter)
(package! pdf-tools)
;; (package! peep-dired)
(package! flycheck-aspell)
(package! calfw)
(package! calfw-org)
(package! org-transclusion)
(package! toc-org)
(package! websocket)
(package! org-roam-ui)
(package! org-timeblock)
(package! magit-todos)
;; (package! consult)
(package! highlight-indent-guides)
;; (package! corfu)
;; (package! orderless)
;; (package! cape)
;; (package! marginalia)
(package! math-preview)
(package! org-download)
;; (package! openwith)
;; (package! ob-mermaid)
;; (package! org-yt)
;; (package! elfeed-protocol)
(package! org-sliced-images)
(package! good-scroll)
(package! all-the-icons-ibuffer)
(package! all-the-icons-dired)
(package! all-the-icons-completion)
(package! org-alert)
