require("scripts.checkbox")
-- require("scripts.daily-notes-markdown")
require("scripts.daily-notes-org")
require("scripts.folding")
require("scripts.get-block-reference")
require("scripts.insert-time")
require("scripts.insert-timestamp")
require("scripts.markdown-formatter")
require("scripts.remove-blank")
require("scripts.tasks")
require("scripts.toggle-wrap")
require("scripts.git")
