use_preview_script true
set preview_script ~/.config/ranger/scope.sh
set preview_images true
set preview_images_method ueberzug
set show_hidden true
set colorscheme n1dh0gg
set editor nvim
map e shell nvim %f
map q quit
map Q shell bash
