#!/usr/bin/env bash

display=$(echo "$XDG_SESSION_TYPE")

while read file; do
	case "$1" in
	"c")
		if [ "$display" = "wayland" ]; then
			wl-copy "$file"
		elif [ "$display" = "x11" ]; then
			xclip -selection clipboard -target image/png "$file"
		fi
		notify-send "$file has been copied!" && exit 0
		;;
	"d")
		choice=$(echo -e "y\nn" | rofi -dmenu)
		if [ "$choice" = "y" ]; then
			rm "$file" && notify-send "$file deleted."
		fi
		;;
	"g")
		gimp "$file"
		;;
	"s")
		satty "$file"
		;;
	"i")
		notify-send "File information" \
			"$(mediainfo "$file" | tr -s ' ' | grep -v CompleteName_Last)"
		;;
	"x")
		if [ "$display" = "wayland" ]; then
			swww img --transition-type=fade "$file"
		elif [ "$display" = "x11" ]; then
			xwallpaper --zoom "$file"
			filename=$HOME/.config/wall
		fi
		if [ ! -f $filename ]; then
			touch $filename
		fi
		path=$(pwd)
		echo "$path/$file" >$HOME/.config/wall && exit
		;;
	esac
done
