#!/usr/bin/env bash

display=$XDG_SESSION_TYPE

while read -r file; do
  case "$1" in
  "c")
    if [ "$display" = "wayland" ]; then
      wl-copy "$file"
    elif [ "$display" = "x11" ]; then
      xclip -selection clipboard -target image/png "$file"
    fi
    notify-send "$file has been copied!" && exit 0
    ;;
  "d")
    choice=$(echo -e "y\nn" | rofi -dmenu)
    if [ "$choice" = "y" ]; then
      rm "$file" && notify-send "$file deleted."
    fi
    ;;
  "g")
    gimp && setsid -f gimp "$file"
    ;;
  "r")
    magick "$file" -rotate 90 "$file"
    ;;
  "R")
    magick "$file" -rotate -90 "$file"
    ;;
  "f")
    magick "$file" -flop "$file"
    ;;
  "i")
    notify-send "File information" \
      "$(mediainfo "$file" | tr -s ' ' | grep -v CompleteName_Last)"
    ;;
  "x")
    xwallpaper --zoom "$file"
    filename=$HOME/.config/wall
    if [ ! -f "$filename" ]; then
      touch "$filename"
    fi
    path=$(pwd)
    echo "$path/$file" >"$HOME/.config/wall" && exit
    ;;
  esac
done
