(defun challenger-font ()
  (interactive)
  (dolist (face
           '((org-level-1 1.3 "#F38BA8" ultra-bold)
             (org-level-2 1.3 "#F3B387" extra-bold)
             (org-level-3 1.3 "#A6E3A1" bold)
             (org-level-4 1.3 "#90E2D5" semi-bold)
             (org-level-5 1.3 "#A0BEFE" normal)
             (org-level-6 1.3 "#cba6cb" normal)
             (org-level-7 1.3 "#46d9ff" normal)
             (org-level-8 1.3 "#ff6c6b" normal)))
    (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
  (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))
(add-hook 'org-mode-hook #'challenger-font)
