#!/bin/env bash

# Commands

## Command Replacement

alias cat='bat'
alias la='eza --color=auto --group-directories-first -a'
alias lda='eza --color=auto --group-directories-first -Da'
alias ld='eza --color=auto --group-directories-first -D'
alias ll='eza --color=auto --group-directories-first -l'
alias ls='eza --color=auto --group-directories-first'

## Default Flags

alias cp="cp --verbose"
alias gemini="gemini -c \$HOME/gemini_cli_config.json"
alias lynx="lynx -cookies -cfg $HOME/.config/lynxrc"
alias rclone="rclone --verbose"
alias rsync="rsync -az"
alias vidir="vidir --verbose"

## Command Shortcuts

alias ctrash='gio trash --empty'                                               # Wipe Trash Bin
alias dmenu="dmenu -b -nf '#ffffff' -nb '#000000' -sb '#1c1c1f' -sf '#7c5cff'" # Dmenu Coloring
alias historyc="rm \$HOME/.zsh_history"                                        # Clear ZSH history
alias lg='lazygit'
alias lgd="lazygit -p \$HOME/dotfiles/"
alias mks="sudo make clean install"
alias nethunter='nmap -v -sn 192.168.0.1/24 | grep -v "host down"'  # Search for all open hosts
alias sshadb="adb forward tcp:8022 tcp:8022; ssh localhost -p 8022" # Use SSH over ADB
alias sxh='nvim $HOME/.config/hypr/modules/keybinds.conf'           # Quick Access to System Bindings
alias v='nvim'

## Script Shortcuts

alias bb="bmark -r list | fzf -m | xargs -I {} xdg-open '{}' " # Shortcuts to interact with taskwarrior
alias fv="sh \$SCRIPTS/__flashcards.sh"                        # Flashcards in the CLI
alias jnd="jn journal day Journals/Daily"                      # Create daily note
alias o="\$HOME/scripts/__obsidian-helper.sh"                  # Obsidian Git Commands
alias rr="ranger_cd"                                           # Change directory for ranger
alias s="\$HOME/.local/bin/search -s"                          # Search the web using Mullvad Leta
alias sm="\$HOME/scripts/sshmanager"                           # Easily access SSH hosts
alias tt="\$HOME/scripts/taskwarrior-helper"                   # Shortcuts to interact with taskwarrior

# Distros

## Arch Linux

if command -v pacman &>/dev/null; then
  alias autoremove='pacman -Qdtq | sudo pacman -Rns -'
  alias clearcache='pacman -Scc'
  alias install='sudo pacman -S'
  alias remove='sudo pacman -Rns'
  alias update='sudo pacman -Syy'
  alias upgrade='sudo pacman -Syu'
fi

## NixOS

alias nx="cd \$HOME/nix/; just"

## Termux

if [ -n "$TERMUX_VERSION" ]; then
  alias autoremove='apt autoremove'
  alias install='pkg install'
  alias remove='pkg uninstall'
  alias update='pkg update'
  alias upgrade='pkg upgrade'
fi

# Nmap: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/nmap/nmap.plugin.zsh

#  -sS - TCP SYN scan
#  -v - verbose
#  -T1 - timing of scan. Options are paranoid (0), sneaky (1), polite (2), normal (3), aggressive (4), and insane (5)
#  -sF - FIN scan (can sneak through non-stateful firewalls)
#  -PE - ICMP echo discovery probe
#  -PP - timestamp discovery probe
#  -PY - SCTP init ping
#  -g - use given number as source port
#  -A - enable OS detection, version detection, script scanning, and traceroute (aggressive)
#  -O - enable OS detection
#  -sA - TCP ACK scan
#  -F - fast scan
#  --script=vuln - also access vulnerabilities in target

alias nmap_open_ports="nmap --open"
alias nmap_list_interfaces="nmap --iflist"
alias nmap_slow="sudo nmap -sS -v -T1"
alias nmap_fin="sudo nmap -sF -v"
alias nmap_full="sudo nmap -sS -T4 -PE -PP -PS80,443 -PY -g 53 -A -p1-65535 -v"
alias nmap_check_for_firewall="sudo nmap -sA -p1-65535 -v -T4"
alias nmap_ping_through_firewall="nmap -PS -PA"
alias nmap_fast="nmap -F -T5 --version-light --top-ports 300"
alias nmap_detect_versions="sudo nmap -sV -p1-65535 -O --osscan-guess -T4 -Pn"
alias nmap_check_for_vulns="nmap --script=vuln"
alias nmap_full_udp="sudo nmap -sS -sU -T4 -A -v -PE -PS22,25,80 -PA21,23,80,443,3389 "
alias nmap_traceroute="sudo nmap -sP -PE -PS22,25,80 -PA21,23,80,3389 -PU -PO --traceroute "
alias nmap_full_with_scripts="sudo nmap -sS -sU -T4 -A -v -PE -PP -PS21,22,23,25,80,113,31339 -PA80,113,443,10042 -PO --script all "
alias nmap_web_safe_osscan="sudo nmap -p 80,443 -O -v --osscan-guess --fuzzy "
alias nmap_ping_scan="nmap -n -sP"

## Deprecated

# alias pdc='fusermount -u -z $BEELZEBUB && notify-send -u normal "Mount" "Drive umounted"'
# alias pdu='pass /dev/atlas | gocryptfs $ATLAS $BEELZEBUB && notify-send -u normal "Mount" "Drive mounted"'
# alias sxhd="$HOME/scripts/__restart-sxhkd.sh" # Quick Access to System Bindings - Xorg only
