#!/usr/bin/env bash

# https://github.com/janpstrunn/dotfiles/blob/main/scripts/repox

# "Quickly clone all Git repos, or fetch all"

DEV_DIR=${DEV:-$HOME/dev}
REPOX_FILE="$HOME/.repox"

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

function help() {
  cat <<EOF
Git Repository Cloner/Fetcher

Usage:
  repox FLAG <FLAG_INPUT> SUB_DIRECTORY
  repox github         # $DEV_DIR/github/
  repox codeberg       # $DEV_DIR/codeberg/

Commands:
  help                        Displays this message and exits

Flags:
  -r                   Use Repox File
  -p <path>            Use a .repox file
EOF
}

function bar() {
  ((current_line++))
  percentage=$((current_line * 100 / total_lines))
  progress_bar="["
  for ((i = 0; i < percentage; i += 5)); do
    progress_bar+="#"
  done
  for ((i = percentage; i < 100; i += 5)); do
    progress_bar+=" "
  done
  progress_bar+="]"
  printf "\r${BLUE}Progress: ${GREEN}%s ${BLUE}%d%% - %s${NC}" "$progress_bar" "$percentage" "$message"
  echo
}

function get_repos() {
  gh repo list | grep "$(whoami)" | awk -F " " '{print $1}' >$TMP_DIR
}

function fetch() {
  current_line=0
  total_lines=$(wc -l <"$TMP_DIR")
  while IFS= read -r repo; do
    if [ -n "$REPOX" ]; then
      repo_name=$(basename "$repo" .git)
    else
      repo_name="$(basename "$repo")"
    fi
    local local_repo="$DEV_DIR/$sub_dir/$repo_name"
    if [ ! -d "$local_repo" ]; then
      if [ "$sub_dir" == "github" ]; then
        if ! gh repo clone "$repo" "$local_repo"; then
          echo "An error occured at $repo"
        fi
      else
        mkdir -p "$DEV_DIR/$sub_dir"
        if ! git -C "$DEV_DIR/$sub_dir" clone "$repo"; then
          echo "An error occured at $repo"
          continue
        fi
      fi
      message="Cloned $repo"
    else
      if ! git -C "$local_repo" fetch; then
        echo "An error occured at $repo"
        continue
      fi
      message="Fetched $repo"
    fi
    bar
  done <"$TMP_DIR"
}

function main() {
  if [ -z "$sub_dir" ]; then
    echo "Missing sub directory!"
    echo "Usage: repox github"
    exit 1
  fi
  if [ -n "$REPOX" ]; then
    TMP_DIR="$REPOX_FILE" # URL to all Git repos
  else
    TMP_DIR="/tmp/repox"
    get_repos # Use gh to get all Github repos
  fi
  fetch
}

while getopts ":hvrp:" opt; do
  case "$opt" in
  h)
    help
    exit 0
    ;;
  r)
    REPOX=true
    ;;
  p)
    REPOX_FILE="$OPTARG"
    ;;
  ?)
    echo "Error: Invalid option '-$OPTARG'" >&2
    exit 1
    ;;
  esac
done

shift $((OPTIND - 1))

case "$1" in
help)
  usage
  exit 0
  ;;
*)
  sub_dir=$1
  main
  ;;
esac
