#!/usr/bin/env bash

# https://github.com/janpstrunn/dotfiles/blob/main/scripts/tskd

# "View your taskwarrior completed tasks using a natural language search"

month_list="January
February
March
April
May
June
July
August
September
October
November
December"

function tskd() {
  local start_date=""
  local end_date=""

  case "$1" in
  *-W[0-9][0-9]) # Matches YYYY-WXX
    year=$(echo "$1" | awk -F '-W' '{print $1}')
    week=$(echo "$1" | awk -F '-W' '{print $2}')
    printf -v week "%02d" "$week"
    start_date=$(date -d "$year-01-04 +$(((week - 1) * 7)) days -$(date -d "$year" +%u) days +1 day" '+%F')
    end_date=$(date -d "$start_date +6 days" '+%F')
    ;;
  [0-9][0-9][0-9][0-9]) # Matches YYYY
    year=$1
    start_date=$year-01-01
    end_date=$(date -d "$start_date +1 year" '+%F')
    ;;
  *-[0-9][0-9]) # Matches YYYY-MM
    year=$(echo "$1" | awk -F '-' '{print $1}')
    month=$(echo "$1" | awk -F '-' '{print $2}')
    start_date="$year"-"$month"-01
    end_date=$(date -d "$start_date +1 month" '+%F')
    ;;
  *)
    if echo "$1" | grep -q "$month_list"; then
      month_name=$(echo "$1" | awk -F ',' '{print $1}')
      year=$(echo "$1" | awk -F ',' '{print $2}')
      month_number=$(date -d "$month_name 1" '+%m')

      start_date="$year-$month_number-01"
      end_date=$(date -d "$start_date +1 month" '+%F')
    else
      if [[ $1 = "" ]]; then # Today
        start_date=$(date '+%F')
        end_date=$(date -d "$start_date +1 day" '+%F')
      else # YYYY-MM-DD
        raw_date="$1"
        polish_date=$(echo "$raw_date" | sed 's/\.md//; s/th//')
        start_date=$(date -d "$polish_date" '+%Y-%m-%d')
        end_date=$(date -d "$start_date +1 day" '+%F')
      fi
    fi
    ;;
  esac

  task "end.after:$start_date" and "end.before:$end_date" completed
}

tskd "$@"
