return {
  "williamboman/mason-lspconfig.nvim",
  opts = {
    ensure_installed = {
      "bashls",
      -- "clangd",
      -- "dockerls",
      -- "efm",
      -- "emmet_ls",
      -- "eslint",
      "gofumpt",
      "goimports",
      "gopls",
      -- "jsonls",
      -- "lua_ls",
      -- "markdown_oxide",
      -- "marksman",
      "prettier",
      -- "pyright",
      "shellcheck",
      "shfmt",
      "stylua",
      -- "tailwindcss",
      -- "ts_ls",
    },
    automatic_installation = true,
  },
  event = "BufReadPre",
  dependencies = "williamboman/mason.nvim",
}
