return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    highlight = { enable = true },
    indent = { enable = true },
    ensure_installed = {
      "bash",
      -- "c",
      "css",
      "diff",
      "dockerfile",
      "gitignore",
      "go",
      "html",
      "hyprlang",
      -- "javascript",
      -- "jsdoc",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      -- "printf",
      "python",
      -- "query",
      "regex",
      -- "rust",
      "toml",
      -- "tsx",
      -- "typescript",
      -- "vim",
      -- "vimdoc",
      -- "xml",
      "yaml",
    },
  },
}
