[general]
import = [
# "~/.config/alacritty/elegant-vagrant-dark.toml",
"~/.config/alacritty/elegant-vagrant-oled.toml",
]

[window]
opacity = 1.0

[font]
size = 11.5

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[scrolling]
history = 5000
multiplier = 3

[bell]
# animation = "Linear"
duration = 0
#color = "#ffffff"
#command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true
