[window]
opacity = 1.0

[font]
size = 11.5

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[scrolling]
history = 5000
multiplier = 3

[colors.primary]
# foreground = "#d8d8d8"
# background = "#101010"
# dim_foreground = "#828482"
# bright_foreground = "None"

[colors]
cursor = { text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }

[colors.search]
matches = { foreground = "#181818", background = "#ac4242" }
focused_match = { foreground = "#181818", background = "#f4bf75" }

[colors.hints]
start = { foreground = "#181818", background = "#f4bf75" }
end = { foreground = "#181818", background = "#ac4242" }

[colors.normal]
black = "#1c1f24"
red = "#d01b24"
green = "#6bbe6c"
yellow = "#f4bf75"
blue = "#2075c7"
magenta = "#c61b6e"
cyan = "#259185"
white = "#e9e2cb"

[colors.bright]
black = "#006388"
red = "#f4153b"
green = "#50ee84"
yellow = "#b17e28"
blue = "#178dc7"
magenta = "#e14d8e"
cyan = "#00b29e"
white = "#fcf4dc"

[colors.dim]
black = "#1c1f24"
red = "#d01b24"
green = "#6bbe6c"
yellow = "#f4bf75"
blue = "#2075c7"
magenta = "#c61b6e"
cyan = "#259185"
white = "#e9e2cb"

[bell]
# animation = "Linear"
duration = 0
#color = "#ffffff"
#command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true
