
[[Snippets]]
  Description = "Extract audio from video"
  Filename = "/home/janpstrunn/.config/pet/snippet.toml"
  Output = ""
  Tag = ["multimedia"]
  command = "ffmpeg -i 1 -vn 2"

[[Snippets]]
  Description = "Convert audio/video"
  Filename = "/home/janpstrunn/.config/pet/snippet.toml"
  Output = ""
  Tag = ["multimedia"]
  command = "ffmpeg -i 1 2"

[[Snippets]]
  Description = "Compress video size"
  Filename = "/home/janpstrunn/.config/pet/snippet.toml"
  Output = ""
  Tag = ["multimedia"]
  command = "ffmpeg -i 1 -vcodec libx265 -crf 2"

[[Snippets]]
  Description = "Remove all metadata from files in the current directory"
  Filename = "/home/janpstrunn/.config/pet/snippet.toml"
  Output = ""
  Tag = ["metadata"]
  command = "exiftool -ALL= ."
